name: 🚀 Feature proposal (Suggestion)
description: I have a suggestion (and may want to implement it)!
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks 😁 for taking the time to fill out this feature proposal!
  - type: textarea
    attributes:
      label: 'Enter your suggestions in details:'
      placeholder: |
        I think it would be great if ...
        I would like to see ...
        I would like to implement ...
    validations:
      required: true